#!/bin/sh
cache_dir="/tmp/rxiv"

get_image(){
[ -d "$cache_dir" ] || mkdir -p "$cache_dir" || exit 1
for i in "$@"; do
    name=${i##*/}
    curl -sL "$i" > "$cache_dir/$name" &&
        files="$files $cache_dir/$name"
done
}

cleanup() {
  rm -f "$cache_dir"/*
}

trap cleanup EXIT
case "$1" in
    -*)
        args=${1}
        shift 1
        # shellcheck disable=2086
        get_image "$@" &&  rxiv $args $files
    ;;

    *http*)
        # shellcheck disable=2086
        get_image "$@" &&  rxiv $files
    ;;

    *)
        printf "error no url nor option\\n" ; exit 1
    ;;
esac
