#!/bin/sh
get_image(){
for i in "$@"; do
    name=${i##*/}
    curl -sL "$i" > "/tmp/${name}" &&
        files=$files" /tmp/${name}"
done
}

cleanup() {
  rm -f $files
}

trap cleanup HUP INT QUIT ABRT TERM
case "$1" in
    -*)
        args=${1}
        shift 1
        # shellcheck disable=2086
        get_image "$@" &&  rxiv $args $files
    ;;

    *http*)
        # shellcheck disable=2086
        get_image "$@" &&  rxiv $files
    ;;

    *)
        printf "error no url nor option\\n" ; exit 1
    ;;
esac
cleanup
