#!/bin/sh
cache_dir="/tmp/rxiv"

get_image(){
[ -d "$cache_dir" ] || mkdir -p "$cache_dir" || exit 1
for i in "$@"; do
    name=${i##*/}
    curl -sL "$i" > "$cache_dir/$name" &&
        files="$files $cache_dir/$name"
done
}

cleanup() {
  rm -f "$cache_dir"/*
}

trap cleanup EXIT
while [ -n "$1" ]; do
    case "$1" in
        -*) args="${args} $1" ;;
        *http*://*.*) urls="${urls} $1" ;;
        *) echo "error no url nor option" > /dev/stderr ; exit 1 ;;
    esac
    shift
done

[ -n "$urls" ] || exit 1
get_image $urls && sxiv $args "$cache_dir"
